# Generated by Django 2.2.3 on 2019-07-19 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='last_recorded_price',
        ),
        migrations.AddField(
            model_name='commodity',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commodity',
            name='change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='previous_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='id',
            field=models.AutoField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
